// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpFjHnkTC-HOde_D0Vgdl8ey56psvXG3Y',
    appId: '1:824657330473:android:016cb8a8d4ea7e59dff738',
    messagingSenderId: '824657330473',
    projectId: 'baligny-6cec8',
    databaseURL: 'https://baligny-6cec8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'baligny-6cec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcygvhq-tuaPnpMfc5q7JWtYzBCFW-gHw',
    appId: '1:824657330473:ios:84dc22a210ce32b3dff738',
    messagingSenderId: '824657330473',
    projectId: 'baligny-6cec8',
    databaseURL: 'https://baligny-6cec8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'baligny-6cec8.firebasestorage.app',
    iosBundleId: 'com.example.baligny',
  );

}